### ISSUE TITLE
it does not compile with rustc v1.44.1

### ISSUE THREAD

**Issue by sassman** [crate-ci/cargo-tarball#133]
There is an issue when building `cargo-tarball` that is related to the used liquid version.

```sh
cargo build
[...]
error[E0283]: type annotations needed
  --> /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/liquid-0.14.3/src/compiler/parser.rs:88:80
   |
88 |                     Token::Identifier(ref x) => indexes.push(Index::with_key(x.as_ref())),
   |                                                                                ^^^^^^ cannot infer type for struct `std::string::String`
   |
   = note: cannot satisfy `std::string::String: std::convert::AsRef<_>`

   Compiling rand_pcg v0.1.1
error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: could not compile `liquid`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It might be useful to upgrade liquid to the latest version.

NOTE: The same error then occurs as well for `stager`, so also there the version of liquid needs to be increased.
